# render.yaml
services:
  - type: web
    name: kind-friend
    env: python
    region: frankfurt
    plan: starter
    autoDeploy: true

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT

    # Your app exposes /ping
    healthCheckPath: /ping

    envVars:
      # --- Core app ---
      - key: APP_SECRET_KEY        # <- matches app.py
        sync: false                # set value in Render dashboard
      - key: APP_TZ
        value: Europe/London
      - key: PUBLIC_URL
        sync: false                # e.g. https://kind-friend.onrender.com
      - key: APP_DB_PATH           # <- point SQLite at the persistent disk
        value: /data/app.db

      # --- OpenAI ---
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL_FREE
        value: gpt-4o-mini
      - key: OPENAI_MODEL_PLUS
        value: gpt-4o-mini
      - key: OPENAI_MODEL_PRO
        value: gpt-4o

      # --- Stripe (live or test) ---
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_PLUS
        sync: false
      - key: STRIPE_PRICE_PRO
        sync: false

    disks:
      - name: data
        mountPath: /data
        sizeGB: 1
